"""Supervisor escalation mechanism for uncertain decisions."""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from orchestrator.tracker_client import TrackerClient

logger = logging.getLogger(__name__)

_AI_TASK_TAG = "ai-task"


def build_escalation_comment(
    reason: str,
    options: list[str],
) -> str:
    """Format a comment explaining supervisor uncertainty.

    Args:
        reason: What the supervisor is uncertain about.
        options: Alternatives being considered.

    Returns:
        Formatted comment text.
    """
    lines = [
        "## Escalation (auto-generated)",
        "",
        f"**Reason:** {reason}",
        "",
    ]

    if options:
        lines.append("**Options being considered:**")
        for i, opt in enumerate(options, 1):
            lines.append(f"{i}. {opt}")
        lines.append("")

    lines.append("_This comment was machine-generated by the AI supervisor. Human review is required._")

    return "\n".join(lines)


async def escalate_to_human(
    tracker_client: TrackerClient,
    issue_key: str,
    reason: str,
    options: list[str],
    tag: str,
) -> str:
    """Escalate an issue for human review.

    Adds the escalation tag, removes ai-task tag (to prevent
    auto-dispatch), and posts a comment with the uncertainty
    explanation.

    Args:
        tracker_client: Yandex Tracker client.
        issue_key: Issue key (e.g., "QR-123").
        reason: What the supervisor is uncertain about.
        options: Alternatives being considered.
        tag: Tag to add for escalation tracking.

    Returns:
        Confirmation message string.
    """
    issue = await asyncio.to_thread(
        tracker_client.get_issue,
        issue_key,
    )

    # Build new tag list: remove ai-task, add escalation tag
    new_tags = [t for t in issue.tags if t != _AI_TASK_TAG]
    if tag not in new_tags:
        new_tags.append(tag)

    await asyncio.to_thread(
        tracker_client.update_issue_tags,
        issue_key,
        new_tags,
    )

    comment = build_escalation_comment(reason, options)
    await asyncio.to_thread(
        tracker_client.add_comment,
        issue_key,
        comment,
    )

    logger.info(
        "Escalated %s for human review: %s",
        issue_key,
        reason,
    )

    return f"Escalated {issue_key} for human review. Tag '{tag}' added, comment posted."
