"""Storage Protocol — abstract interface for persistence backends.

Any class implementing these methods is a valid storage backend.
Current implementation: SQLiteStorage (sqlite_storage.py).
"""

from __future__ import annotations

from typing import Protocol

from orchestrator.stats_models import (
    DeferredTaskRecord,
    EpicChildRecord,
    EpicStateRecord,
    ErrorLogEntry,
    NeedsInfoTrackingRecord,
    ProposalRecord,
    PRTrackingData,
    RecoveryRecord,
    SupervisorRun,
    TaskCostSummary,
    TaskRun,
)


class Storage(Protocol):
    """Abstract storage interface for the orchestrator.

    Defines all persistence operations. Implementations must provide
    all methods below. In Python this is a structural (duck-typed)
    protocol — no inheritance required.

    To swap backends (e.g. PostgreSQL), create a new class that
    implements these methods and pass it wherever Storage is expected.
    """

    async def open(self) -> None: ...
    async def close(self) -> None: ...

    # ---- Task runs ----
    async def record_task_run(self, run: TaskRun) -> None: ...
    async def record_supervisor_run(self, run: SupervisorRun) -> None: ...
    async def has_successful_task_run(self, task_key: str) -> bool: ...
    async def has_unmerged_pr(self, task_key: str) -> bool: ...
    async def get_latest_session_id(self, task_key: str) -> str | None: ...

    # ---- PR lifecycle ----
    async def record_pr_tracked(self, task_key: str, pr_url: str, tracked_at: float) -> None: ...
    async def record_pr_merged(self, task_key: str, pr_url: str, merged_at: float) -> None: ...
    async def record_pr_cancelled(self, task_key: str, cancelled_at: float) -> None: ...
    async def record_pr_verified(self, task_key: str, verified_at: float) -> None: ...
    async def increment_review_iterations(self, task_key: str) -> None: ...
    async def increment_ci_failures(self, task_key: str) -> None: ...

    # ---- Error log ----
    async def record_error(self, entry: ErrorLogEntry) -> None: ...

    # ---- Queries ----
    async def get_task_cost_summary(
        self,
        task_key: str,
    ) -> TaskCostSummary: ...
    async def get_summary(self, days: int = 7, since: float | None = None) -> dict: ...
    async def get_costs(
        self, group_by: str = "model", days: int = 7, limit: int = 50, since: float | None = None
    ) -> list[dict]: ...
    async def get_recent_tasks(self, limit: int = 20) -> list[dict]: ...
    async def get_error_stats(self, days: int = 7, since: float | None = None) -> list[dict]: ...
    async def execute_readonly(self, sql: str, limit: int = 100, timeout_seconds: float = 5.0) -> list[dict]: ...

    # ---- Proposals ----
    async def resolve_proposal(self, proposal_id: str, status: str, resolved_at: float) -> None: ...
    async def get_proposal_stats(self, days: int = 7, since: float | None = None) -> dict: ...

    # ---- Recovery ----
    async def upsert_recovery_state(self, record: RecoveryRecord) -> None: ...
    async def record_recovery_attempt(
        self, issue_key: str, timestamp: float, category: str, error_message: str
    ) -> None: ...
    async def delete_recovery(self, issue_key: str) -> None: ...
    async def load_recovery_states(self) -> list[RecoveryRecord]: ...
    async def load_recovery_attempts(self, issue_key: str) -> list[tuple[float, str, str]]: ...

    # ---- Epic coordinator ----
    async def upsert_epic_state(self, record: EpicStateRecord) -> None: ...
    async def upsert_epic_child(self, epic_key: str, child: EpicChildRecord) -> None: ...
    async def delete_epic(self, epic_key: str) -> None: ...
    async def load_epic_states(self) -> list[EpicStateRecord]: ...
    async def load_epic_children(self, epic_key: str) -> list[EpicChildRecord]: ...

    # ---- PR tracking dedup ----
    async def upsert_pr_tracking(self, data: PRTrackingData) -> None: ...
    async def delete_pr_tracking(self, task_key: str) -> None: ...
    async def load_pr_tracking(
        self,
        task_key: str | None = None,
    ) -> list[PRTrackingData]: ...

    # ---- Needs-info tracking ----
    async def upsert_needs_info_tracking(self, record: NeedsInfoTrackingRecord) -> None: ...
    async def delete_needs_info_tracking(self, issue_key: str) -> None: ...
    async def load_needs_info_tracking(self) -> list[NeedsInfoTrackingRecord]: ...

    # ---- Proposals extended ----
    async def upsert_proposal(self, record: ProposalRecord) -> None: ...
    async def load_proposals(self) -> list[dict]: ...

    # ---- Deferred tasks (dependency manager) ----
    async def upsert_deferred_task(self, record: DeferredTaskRecord) -> None: ...
    async def delete_deferred_task(self, issue_key: str) -> None: ...
    async def load_deferred_tasks(self) -> list[DeferredTaskRecord]: ...

    # ---- Events ----
    async def save_event(self, event_type: str, task_key: str, data: str, timestamp: float) -> None: ...
    async def save_events_batch(self, events: list[tuple[str, str, str, float]]) -> None: ...
    async def load_events_for_task(self, task_key: str, limit: int = 500) -> list[dict]: ...
    async def load_recent_events(self, limit: int = 5000) -> list[dict]: ...
    async def delete_old_events(self, before_timestamp: float) -> int: ...

    # ---- Environment config ----
    async def get_environment(self, name: str) -> dict | None: ...
    async def set_environment(self, name: str, config: dict, updated_by: str) -> None: ...
    async def list_environments(self) -> list[dict]: ...
    async def delete_environment(self, name: str) -> None: ...
